/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2020-04-27 10:25:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class after_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\">\n");
      out.write("\t<link href=\"http://fonts.googleapis.com/css?family=Cookie\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("    \n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react-dom.min.js\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t<meta name=\"keywords\" content=\"footer, address, phone, icons\" />\n");
      out.write("    \n");
      out.write("    <link rel=stylesheet href=\"home.css\">\n");
      out.write("    <script src=\"home.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body onload=\"noBack();\"onpageshow=\"if (event.persisted) noBack();\" onunload=\"\">\n");
      out.write("<SCRIPT type=\"text/javascript\">\n");
      out.write("    window.history.forward();\n");
      out.write("    function noBack() { window.history.forward(); }\n");
      out.write("</SCRIPT>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("<div class=\"header\">\n");
      out.write("  <input type=\"checkbox\" class=\"openSidebarMenu\" id=\"openSidebarMenu\">\n");
      out.write("  <label for=\"openSidebarMenu\" class=\"sidebarIconToggle\">\n");
      out.write("    <div class=\"spinner diagonal part-1\"></div>\n");
      out.write("    <div class=\"spinner horizontal\"></div>\n");
      out.write("    <div class=\"spinner diagonal part-2\"></div>\n");
      out.write("  </label>\n");
      out.write("  <div id=\"sidebarMenu\">\n");
      out.write("    <ul class=\"sidebarMenuInner\">\n");
      out.write("      <li><a href=\"https://vanila.io\" target=\"_blank\">Company</a></li>\n");
      out.write("      <li><a href=\"https://instagram.com/plavookac\" target=\"_blank\">Instagram</a></li>\n");
      out.write("      <li><a href=\"https://twitter.com/plavookac\" target=\"_blank\">Twitter</a></li>\n");
      out.write("      <li><a href=\"https://www.youtube.com/channel/UCDfZM0IK6RBgud8HYGFXAJg\" target=\"_blank\">YouTube</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </div>\n");
      out.write("  <img src=\"skilllogo.jpg\">\n");
      out.write("  <a class=\"active\" href=\"#\"><i class=\"fa fa-fw fa-home\"></i> HOME</a>\n");
      out.write("  <a href=\"dashboard.jsp\"><i class=\"fa fa-fw fa-tachometer\"></i> DASHBOARD</a>\n");
      out.write("  <a href=\"history.jsp\"><i class=\"fa fa-fw fa-history\"></i> TEST HISTORY</a>\n");
      out.write("  <a href=\"logout.jsp\"><i class=\"fa fa-fw fa-user\"></i> LOGOUT</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("<!--********************************************************************************-->\n");
      out.write("        \n");
      out.write("<!--<div id=\"box\"></div>-->\n");
      out.write("<img src=\"2.png\" style=\"width: 100%;height: 50%; position: relative;top: 100px;\">\n");
      out.write("\n");
      out.write("<!--***********************************************************************************-->\n");
      out.write("        \n");
      out.write("<div>\n");
      out.write("  <div class=\"row aft-banner\" style=\"position: relative;top: 90px;font-size: 20px;\">\n");
      out.write("        <div class=\"col-sm-1\"></div>\n");
      out.write("        <div class=\"col-sm-2 d-none d-sm-block\"></div>\n");
      out.write("        <div class=\"col-sm-4\" \"width:50%;\">\n");
      out.write("        <div class=\"text-center orange\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ONLINE QUIZ SYSTEM</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-sm-4\"></div>\n");
      out.write("  </div>\n");
      out.write("</div>   \n");
      out.write("        \n");
      out.write("<!--***********************************************************************************-->\n");
      out.write("\n");
      out.write("<div class=\"smoke\">\n");
      out.write("  <div class=\"container\" id=\"fh5co-pricing\">\n");
      out.write("  <div class=\"heading animate-box\"><h2><center><b>MEET OUR TEAM</b></center></h2></div>\n");
      out.write("  <br><br>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-sm-4 animate-box\" data-animate-effect=\"fadeInLeft\">\n");
      out.write("                <div class=\"price-box\">\n");
      out.write("                    <h3><b>AYUSH JAIN</b></h3>\n");
      out.write("                    <h3><b>B_TECH</b></h3>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>COMPUTER SCIENCE</div>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>ayushdagda19@gmail.com</div>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>DESIGNER</div>\n");
      out.write("                    <br>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4\">\n");
      out.write("                <div class=\"price-box-dark animate-box\">\n");
      out.write("                    <h3><b>ABHISHEK AHUJA</b></h3>\n");
      out.write("                  \n");
      out.write("                    <h3><b>B_TECH</b></h3>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>COMPUTER SCIENCE</div>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>abhikumarshek14@gmail.com</div>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>CODING</div>\n");
      out.write("                    <br>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4\">\n");
      out.write("                <div class=\"price-box animate-box\" data-animate-effect=\"fadeInRight\">\n");
      out.write("                    <h3><b>AYUSH SAHU</b></h3>\n");
      out.write("                   \n");
      out.write("                    <h3><b>B-TECH</b></h3>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>COMPUTER SCIENCE</div>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>ayushsahu599@gmail.com</div>\n");
      out.write("                    <div class=\"gr-line\"></div>\n");
      out.write("                    <div>DESIGNER</div>\n");
      out.write("                    <br>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write(" \n");
      out.write("<!--************************************************************************************-->\n");
      out.write("        \n");
      out.write("<div class=\"white\">\n");
      out.write("    <div class=\"container\" id=\"fh5co-features\">\n");
      out.write("        <div class=\"heading animate-box\"><h2><b><span class=\"text-org\">OUR</span> <span class=\"text-gr\"> FEATURES</span></b></h2>\n");
      out.write("        </div>\n");
      out.write("        <br><br>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-sm-4 animate-box\" data-animate-effect=\"fadeIn\">\n");
      out.write("                <div class=\"bordery\">\n");
      out.write("                    <i class=\"fa fa-server text-gr bfont\" aria-hidden=\"true\"></i> <b>Large number</b>\n");
      out.write("                    <div class=\"features\">Taking online quizzes makes it possible to have a large number of participants. It could be up to a number of 1000 participants (and even more!). It doesn?t matter at what kind of location they take the online quiz as long as they are connected to the Internet.\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4 animate-box\" data-animate-effect=\"fadeIn\">\n");
      out.write("                <div class=\"bordery\">\n");
      out.write("                    <i class=\"fa fa-server text-gr bfont\" aria-hidden=\"true\"></i> <b>No instructor needed</b>\n");
      out.write("                    <div class=\"features\">Quizzess can be given without instructor which saves money and time...\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4 animate-box\" data-animate-effect=\"fadeIn\">\n");
      out.write("                <div class=\"bordery\" style=\"border-right: 0px;\">\n");
      out.write("                    <i class=\"fa fa-server text-gr bfont\" aria-hidden=\"true\"></i> Quiz results<b></b>\n");
      out.write("                    <div class=\"features\">\n");
      out.write("Another plus of online quizzes is getting immediate results from your participants. Not only does the creator get the results, the participant itself is also possible to get his or her results. This makes it for the creator easy to identify the gaps in knowledge. The participants are able to view on what kind of section they have to improve themselves.\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4 animate-box\">\n");
      out.write("                <div class=\"bordery\" style=\"border-bottom: 0px;\">\n");
      out.write("                    <i class=\"fa fa-server text-gr bfont\" aria-hidden=\"true\"></i> <b>Timer</b>\n");
      out.write("                    <div class=\"features\">User improve time by time because of timer in quiz and every next time on give test he/she give test very quickly than time...\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4 animate-box\">\n");
      out.write("                <div class=\"bordery\" style=\"border-bottom: 0px\">\n");
      out.write("                    <i class=\"fa fa-server text-gr bfont\" aria-hidden=\"true\"></i> <b>Different Languages</b>\n");
      out.write("                    <div class=\"features\">User can give test on different languages as per their choose language...\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-4 animate-box\">\n");
      out.write("                <div class=\"bordery\" style=\"border-right: 0px; border-bottom: 0px\">\n");
      out.write("                    <i class=\"fa fa-server text-gr bfont\" aria-hidden=\"true\"></i> <b>Free Domain Transfer</b>\n");
      out.write("                    <div class=\"features\">Get amazing results working with the best programmers, designers, writers and\n");
      out.write("                        other top online pros. You can hire us with confidence. Get amazing results working with the\n");
      out.write("                        best programmers...\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--**************************************************************************************      -->\n");
      out.write("        \n");
      out.write("        <footer class=\"new_footer_area bg_color\">\n");
      out.write("            <div class=\"new_footer_top\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                            <div class=\"f_widget company_widget wow fadeInLeft\" data-wow-delay=\"0.2s\" style=\"visibility: visible; animation-delay: 0.2s; animation-name: fadeInLeft;\">\n");
      out.write("                                <h3 class=\"f-title f_600 t_color f_size_18\">Get in Touch</h3>\n");
      out.write("                                <p>To access the content please get Register and practice!</p>\n");
      out.write("                                    <button class=\"btn btn_get btn_get_two\" type=\"submit\" onclick=\"location.href='login.jsp'\">REGISTER </button>\n");
      out.write("                                    <p class=\"mchimp-errmessage\" style=\"display: none;\"></p>\n");
      out.write("                                    <p class=\"mchimp-sucmessage\" style=\"display: none;\"></p>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("            \n");
      out.write("                        <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                            <div class=\"f_widget about-widget pl_70 wow fadeInLeft\" data-wow-delay=\"0.6s\" style=\"visibility: visible; animation-delay: 0.6s; animation-name: fadeInLeft;\">\n");
      out.write("                                <h3 class=\"f-title f_600 t_color f_size_18\">CONTENT</h3>\n");
      out.write("                                <ul class=\"list-unstyled f_list\">\n");
      out.write("                                    <li><a href=\"index.html\">HOME</a></li>\n");
      out.write("                                    <li><a href=\"login.jsp\">LOGIN</a></li>\n");
      out.write("                                    <li><a href=\"about.jsp\">ABOUT US</a></li>\n");
      out.write("                                    <li><a href=\"contact.jsp\">CONTACT US</a></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                            <div class=\"f_widget about-widget pl_70 wow fadeInLeft\" data-wow-delay=\"0.6s\" style=\"visibility: visible; animation-delay: 0.6s; animation-name: fadeInLeft;\">\n");
      out.write("                                <h3 class=\"f-title f_600 t_color f_size_18\">CONNECT</h3>\n");
      out.write("                                <ul class=\"list-unstyled f_list\" style=\"color:#6a7695;\">\n");
      out.write("                                    <li><b>INDORE, MADHYA PRADESH</b></li>\n");
      out.write("                                    <li><b>CONTACT : 9479543431 , 9826315789</b></li>\n");
      out.write("                                    <li><b>9669261408</b></li>\n");
      out.write("                                    <li><b>Email : onlinequizsystem66@gmail.com</b></li>\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-3 col-md-6\">\n");
      out.write("                            <div class=\"f_widget social-widget pl_70 wow fadeInLeft\" data-wow-delay=\"0.8s\" style=\"visibility: visible; animation-delay: 0.8s; animation-name: fadeInLeft;\">\n");
      out.write("                                <h3 class=\"f-title f_600 t_color f_size_18\">See our Profiles</h3>\n");
      out.write("                                <div class=\"f_social_icon\">\n");
      out.write("                                    <a href=\"#\" class=\"fa fa-facebook\"></a>\n");
      out.write("                                    <a href=\"#\" class=\"fa fa-twitter\"></a>\n");
      out.write("                                    <a href=\"#\" class=\"fa fa-linkedin\"></a>\n");
      out.write("                                    <a href=\"#\" class=\"fa fa-pinterest\"></a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"footer_bg\">\n");
      out.write("                    <div class=\"footer_bg_one\"></div>\n");
      out.write("                    <div class=\"footer_bg_two\"></div>\n");
      out.write("                </div>\n");
      out.write("    </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
